//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importVtd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ImpVtd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources_ImpVtd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("importVtd.Resources.Resources_ImpVtd", typeof(Resources_ImpVtd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ файла.
        /// </summary>
        public static string btnAnalizeFile {
            get {
                return ResourceManager.GetString("btnAnalizeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать импорт.
        /// </summary>
        public static string buAddNewImport {
            get {
                return ResourceManager.GetString("buAddNewImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить импорт.
        /// </summary>
        public static string buDeleteImport {
            get {
                return ResourceManager.GetString("buDeleteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить увязку.
        /// </summary>
        public static string BuDictDefectDeleteMap {
            get {
                return ResourceManager.GetString("BuDictDefectDeleteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязать.
        /// </summary>
        public static string BuDictDefectMap {
            get {
                return ResourceManager.GetString("BuDictDefectMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных.
        /// </summary>
        public static string BusyContent {
            get {
                return ResourceManager.GetString("BusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить без увязки.
        /// </summary>
        public static string cAddWithoutLink {
            get {
                return ResourceManager.GetString("cAddWithoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шов, час.
        /// </summary>
        public static string cAngleHour {
            get {
                return ResourceManager.GetString("cAngleHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить автоматическую увязку.
        /// </summary>
        public static string cAutoLink {
            get {
                return ResourceManager.GetString("cAutoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний коэффициент на участке.
        /// </summary>
        public static string cAverageCoefficientOnASite {
            get {
                return ResourceManager.GetString("cAverageCoefficientOnASite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плотность реперов на 1 км.
        /// </summary>
        public static string cBenchmarkDensityPerKm {
            get {
                return ResourceManager.GetString("cBenchmarkDensityPerKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя связать {0} и {1}, уже увязано два трубных элемента.
        /// </summary>
        public static string cCantLinkBecauseLimit {
            get {
                return ResourceManager.GetString("cCantLinkBecauseLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите данные....
        /// </summary>
        public static string cChoose {
            get {
                return ResourceManager.GetString("cChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить доступ к файлу.
        /// </summary>
        public static string cCouldNotLoadFile {
            get {
                return ResourceManager.GetString("cCouldNotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трещиноподобные дефекты, шт..
        /// </summary>
        public static string cCrackLikeDefects {
            get {
                return ResourceManager.GetString("cCrackLikeDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт данных.
        /// </summary>
        public static string cDataImport {
            get {
                return ResourceManager.GetString("cDataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт данных завершился.
        /// </summary>
        public static string cDataImportIsEnded {
            get {
                return ResourceManager.GetString("cDataImportIsEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние импорта данных.
        /// </summary>
        public static string cDataImportState {
            get {
                return ResourceManager.GetString("cDataImportState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БД.
        /// </summary>
        public static string cDB {
            get {
                return ResourceManager.GetString("cDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество дефектов.
        /// </summary>
        public static string cDefectNumber {
            get {
                return ResourceManager.GetString("cDefectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во деф..
        /// </summary>
        public static string cDefects {
            get {
                return ResourceManager.GetString("cDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словарь дефектов.
        /// </summary>
        public static string cDefectsDictionary {
            get {
                return ResourceManager.GetString("cDefectsDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дефекта.
        /// </summary>
        public static string cDefectType {
            get {
                return ResourceManager.GetString("cDefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет прав на удаление импорта.
        /// </summary>
        public static string cErrUnpermittedDeleteImport {
            get {
                return ResourceManager.GetString("cErrUnpermittedDeleteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string cFile {
            get {
                return ResourceManager.GetString("cFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дефекты формы, шт..
        /// </summary>
        public static string cFormDefects {
            get {
                return ResourceManager.GetString("cFormDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт данных завершился с ошибкой.
        /// </summary>
        public static string cImportEndedWithError {
            get {
                return ResourceManager.GetString("cImportEndedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процедура импорта запущена, импорт: .
        /// </summary>
        public static string cImportIsRun1 {
            get {
                return ResourceManager.GetString("cImportIsRun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  нельзя начать новый импорт или продолжить не завершенный.
        /// </summary>
        public static string cImportIsRun2 {
            get {
                return ResourceManager.GetString("cImportIsRun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется импорт.
        /// </summary>
        public static string cImportIsRunning {
            get {
                return ResourceManager.GetString("cImportIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние импорта.
        /// </summary>
        public static string cImportStatus {
            get {
                return ResourceManager.GetString("cImportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to км.
        /// </summary>
        public static string cKm {
            get {
                return ResourceManager.GetString("cKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КМ, м.
        /// </summary>
        public static string cKmM {
            get {
                return ResourceManager.GetString("cKmM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км по МГ, м.
        /// </summary>
        public static string cKmOnMg {
            get {
                return ResourceManager.GetString("cKmOnMg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км по ВТД, м.
        /// </summary>
        public static string cKmOnVtd {
            get {
                return ResourceManager.GetString("cKmOnVtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний импорт завершился с ошибкой.
        /// </summary>
        public static string cLastImportWithError {
            get {
                return ResourceManager.GetString("cLastImportWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раскладка труб.
        /// </summary>
        public static string cLayoutOfPipe {
            get {
                return ResourceManager.GetString("cLayoutOfPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина, км.
        /// </summary>
        public static string cLengthKm {
            get {
                return ResourceManager.GetString("cLengthKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина, м.
        /// </summary>
        public static string cLengthM {
            get {
                return ResourceManager.GetString("cLengthM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество связанных реперов, шт..
        /// </summary>
        public static string cLinkedBenchmarkNumber {
            get {
                return ResourceManager.GetString("cLinkedBenchmarkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные трубные элементы.
        /// </summary>
        public static string cLinkedPipeMountingComponents {
            get {
                return ResourceManager.GetString("cLinkedPipeMountingComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязывание реперов.
        /// </summary>
        public static string cLinkingReper {
            get {
                return ResourceManager.GetString("cLinkingReper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        public static string cM {
            get {
                return ResourceManager.GetString("cM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество магнитных аномалий, шт..
        /// </summary>
        public static string cMagneticAnomalyNumber {
            get {
                return ResourceManager.GetString("cMagneticAnomalyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string cNoData {
            get {
                return ResourceManager.GetString("cNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string cNumber {
            get {
                return ResourceManager.GetString("cNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нерасчетные аномалии, шт..
        /// </summary>
        public static string cOffDesignAnomalies {
            get {
                return ResourceManager.GetString("cOffDesignAnomalies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество трубных элементов, шт..
        /// </summary>
        public static string cPipeElementNumber {
            get {
                return ResourceManager.GetString("cPipeElementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раскладка труб.
        /// </summary>
        public static string cPipeJornal {
            get {
                return ResourceManager.GetString("cPipeJornal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется импорт, нельзя начать новый импорт или продолжить не завершенный.
        /// </summary>
        public static string cRunningImportAnotherDeny {
            get {
                return ResourceManager.GetString("cRunningImportAnotherDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать импорт.
        /// </summary>
        public static string cStartImport {
            get {
                return ResourceManager.GetString("cStartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика импорта.
        /// </summary>
        public static string cStaticticsOfImport {
            get {
                return ResourceManager.GetString("cStaticticsOfImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string cStatistics {
            get {
                return ResourceManager.GetString("cStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика дефектов по группам.
        /// </summary>
        public static string cStatisticsOfDefectsByGroups {
            get {
                return ResourceManager.GetString("cStatisticsOfDefectsByGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стресс-коррозии, шт..
        /// </summary>
        public static string cStressCorrosion {
            get {
                return ResourceManager.GetString("cStressCorrosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трубные элементы из БД.
        /// </summary>
        public static string cTemFromDB {
            get {
                return ResourceManager.GetString("cTemFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трубные элементы из файла импорта ВТД.
        /// </summary>
        public static string cTemFromFile {
            get {
                return ResourceManager.GetString("cTemFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина, мм.
        /// </summary>
        public static string cThicknessMm {
            get {
                return ResourceManager.GetString("cThicknessMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string cType {
            get {
                return ResourceManager.GetString("cType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аномалии шва, шт..
        /// </summary>
        public static string cWeldAnomalies {
            get {
                return ResourceManager.GetString("cWeldAnomalies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррозионные дефекты, шт..
        /// </summary>
        public static string cСorrosionDefects {
            get {
                return ResourceManager.GetString("cСorrosionDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления импорта.
        /// </summary>
        public static string ErrorDeleteImport {
            get {
                return ResourceManager.GetString("ErrorDeleteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные типы дефектов.
        /// </summary>
        public static string gbDictDefectCompar {
            get {
                return ResourceManager.GetString("gbDictDefectCompar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не связанные типы дефектов из файла импорта.
        /// </summary>
        public static string gbDictDefectFileImport {
            get {
                return ResourceManager.GetString("gbDictDefectFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы дефектов из БД.
        /// </summary>
        public static string gbDictDefectTypeBD {
            get {
                return ResourceManager.GetString("gbDictDefectTypeBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало, км.
        /// </summary>
        public static string gbNewImportBegin {
            get {
                return ResourceManager.GetString("gbNewImportBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string gbNewImportData {
            get {
                return ResourceManager.GetString("gbNewImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор.
        /// </summary>
        public static string gbNewImportDogovor {
            get {
                return ResourceManager.GetString("gbNewImportDogovor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец, км.
        /// </summary>
        public static string gbNewImportEnd {
            get {
                return ResourceManager.GetString("gbNewImportEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеральный подрядчик.
        /// </summary>
        public static string gbNewImportGenPod {
            get {
                return ResourceManager.GetString("gbNewImportGenPod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель работ.
        /// </summary>
        public static string gbNewImportispolWorc {
            get {
                return ResourceManager.GetString("gbNewImportispolWorc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МГ.
        /// </summary>
        public static string gbNewImportMG {
            get {
                return ResourceManager.GetString("gbNewImportMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нитка.
        /// </summary>
        public static string gbNewImportPipe {
            get {
                return ResourceManager.GetString("gbNewImportPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место работ.
        /// </summary>
        public static string gbNewImportPlaseWork {
            get {
                return ResourceManager.GetString("gbNewImportPlaseWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок.
        /// </summary>
        public static string gbNewImportSection {
            get {
                return ResourceManager.GetString("gbNewImportSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные объекты на участке.
        /// </summary>
        public static string gbReperLink {
            get {
                return ResourceManager.GetString("gbReperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дефекта из БД.
        /// </summary>
        public static string grdCompareDefectColumn1 {
            get {
                return ResourceManager.GetString("grdCompareDefectColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название группы.
        /// </summary>
        public static string grdCompareDefectColumn2 {
            get {
                return ResourceManager.GetString("grdCompareDefectColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип объекта из файла.
        /// </summary>
        public static string grdCompareDefectColumn3 {
            get {
                return ResourceManager.GetString("grdCompareDefectColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название группы.
        /// </summary>
        public static string grdTypeDefectColum2 {
            get {
                return ResourceManager.GetString("grdTypeDefectColum2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий статус.
        /// </summary>
        public static string gridStatecState {
            get {
                return ResourceManager.GetString("gridStatecState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата импорта.
        /// </summary>
        public static string gridStateDataImport {
            get {
                return ResourceManager.GetString("gridStateDataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата проведения.
        /// </summary>
        public static string gridStatedateContract {
            get {
                return ResourceManager.GetString("gridStatedateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string gridStateFIO {
            get {
                return ResourceManager.GetString("gridStateFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название файла.
        /// </summary>
        public static string gridStateNameFile {
            get {
                return ResourceManager.GetString("gridStateNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер договора.
        /// </summary>
        public static string gridStateNumberContract {
            get {
                return ResourceManager.GetString("gridStateNumberContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок газопровода.
        /// </summary>
        public static string gridStateSectionPipeline {
            get {
                return ResourceManager.GetString("gridStateSectionPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные по договору.
        /// </summary>
        public static string groupBoxNewImportDataDog {
            get {
                return ResourceManager.GetString("groupBoxNewImportDataDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные по выбранному участку.
        /// </summary>
        public static string groupBoxNewImportDataSect {
            get {
                return ResourceManager.GetString("groupBoxNewImportDataSect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла.
        /// </summary>
        public static string groupBoxNewImportDownLoad {
            get {
                return ResourceManager.GetString("groupBoxNewImportDownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор протяженного объекта.
        /// </summary>
        public static string groupBoxNewImportVubor {
            get {
                return ResourceManager.GetString("groupBoxNewImportVubor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для данного участка.
        /// </summary>
        public static string linkNoReperBD {
            get {
                return ResourceManager.GetString("linkNoReperBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сопоставления строк.
        /// </summary>
        public static string Message21 {
            get {
                return ResourceManager.GetString("Message21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления связи.
        /// </summary>
        public static string MessageBoxDictDefect1 {
            get {
                return ResourceManager.GetString("MessageBoxDictDefect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка увязывания словарей.
        /// </summary>
        public static string MessageBoxDictDefect2 {
            get {
                return ResourceManager.GetString("MessageBoxDictDefect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить импорт ВТД?.
        /// </summary>
        public static string msgDelImport {
            get {
                return ResourceManager.GetString("msgDelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        public static string msgDelImportAttantion {
            get {
                return ResourceManager.GetString("msgDelImportAttantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для продолжения импорта необходимо увязать реперы.
        /// </summary>
        public static string ReperBuNextMessage {
            get {
                return ResourceManager.GetString("ReperBuNextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реперы из БД.
        /// </summary>
        public static string Repergb1 {
            get {
                return ResourceManager.GetString("Repergb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реперы из файла импорта ВТД.
        /// </summary>
        public static string Repergb2 {
            get {
                return ResourceManager.GetString("Repergb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные объекты на участке.
        /// </summary>
        public static string Repergb3 {
            get {
                return ResourceManager.GetString("Repergb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔКм по МГ, м.
        /// </summary>
        public static string ReperLenMG {
            get {
                return ResourceManager.GetString("ReperLenMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔКм по ВТД, м.
        /// </summary>
        public static string ReperLenVTD {
            get {
                return ResourceManager.GetString("ReperLenVTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МК.
        /// </summary>
        public static string ReperMK {
            get {
                return ResourceManager.GetString("ReperMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string ReperName {
            get {
                return ResourceManager.GetString("ReperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер связи.
        /// </summary>
        public static string ReperNumberLink {
            get {
                return ResourceManager.GetString("ReperNumberLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество секций.
        /// </summary>
        public static string ReperNumberSec {
            get {
                return ResourceManager.GetString("ReperNumberSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип объекта.
        /// </summary>
        public static string ReperTypeobj {
            get {
                return ResourceManager.GetString("ReperTypeobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор исходных данных.
        /// </summary>
        public static string statusChooseImpData {
            get {
                return ResourceManager.GetString("statusChooseImpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен с ошибкой.
        /// </summary>
        public static string statusErrCompl {
            get {
                return ResourceManager.GetString("statusErrCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязывание трубных журналов.
        /// </summary>
        public static string statusLinkSection {
            get {
                return ResourceManager.GetString("statusLinkSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен успешно.
        /// </summary>
        public static string statusSucessCompl {
            get {
                return ResourceManager.GetString("statusSucessCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор исходных данных.
        /// </summary>
        public static string tabItemSelectdate {
            get {
                return ResourceManager.GetString("tabItemSelectdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История изменений.
        /// </summary>
        public static string tabItemStateProcess {
            get {
                return ResourceManager.GetString("tabItemStateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История проведения импортов.
        /// </summary>
        public static string tbNameHistory {
            get {
                return ResourceManager.GetString("tbNameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На выбранном участке ВТД и на основании договора.
        /// </summary>
        public static string tbNoDataDog1 {
            get {
                return ResourceManager.GetString("tbNoDataDog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уже ранее был произведен импорт данных ВТД. Для проведения импорта данных на основании договора.
        /// </summary>
        public static string tbNoDataDog2 {
            get {
                return ResourceManager.GetString("tbNoDataDog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to необходимо удалить предыдущий импорт ВТД, выполненный на его основании.
        /// </summary>
        public static string tbNoDataDog3 {
            get {
                return ResourceManager.GetString("tbNoDataDog3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите иной номер договора на проведение ВТД.
        /// </summary>
        public static string tbNoDataDog4 {
            get {
                return ResourceManager.GetString("tbNoDataDog4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат анализа файла.
        /// </summary>
        public static string tbResultAnalizFile {
            get {
                return ResourceManager.GetString("tbResultAnalizFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина по МГ, м.
        /// </summary>
        public static string tubeJornalLenghtMG {
            get {
                return ResourceManager.GetString("tubeJornalLenghtMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина по ВТД, м.
        /// </summary>
        public static string tubeJornalLenghtVTD {
            get {
                return ResourceManager.GetString("tubeJornalLenghtVTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество дефектов, шт..
        /// </summary>
        public static string tubeJornalNumberD {
            get {
                return ResourceManager.GetString("tubeJornalNumberD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер трубы.
        /// </summary>
        public static string tubeJornalNumberTube {
            get {
                return ResourceManager.GetString("tubeJornalNumberTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок увязки.
        /// </summary>
        public static string tubeJornalSecLink {
            get {
                return ResourceManager.GetString("tubeJornalSecLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина стенки, мм.
        /// </summary>
        public static string tubeJornalThick {
            get {
                return ResourceManager.GetString("tubeJornalThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип трубы.
        /// </summary>
        public static string tubeJornalType {
            get {
                return ResourceManager.GetString("tubeJornalType", resourceCulture);
            }
        }
    }
}
