//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importVtd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ImpVtd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources_ImpVtd()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("importVtd.Resources.Resources_ImpVtd", typeof(Resources_ImpVtd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ файла.
        /// </summary>
        internal static string btnAnalizeFile {
            get {
                return ResourceManager.GetString("btnAnalizeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый импорт.
        /// </summary>
        internal static string buAddNewImport {
            get {
                return ResourceManager.GetString("buAddNewImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить импорт.
        /// </summary>
        internal static string buDeleteImport {
            get {
                return ResourceManager.GetString("buDeleteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить увязку.
        /// </summary>
        internal static string BuDictDefectDeleteMap {
            get {
                return ResourceManager.GetString("BuDictDefectDeleteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязать.
        /// </summary>
        internal static string BuDictDefectMap {
            get {
                return ResourceManager.GetString("BuDictDefectMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных.
        /// </summary>
        internal static string BusyContent {
            get {
                return ResourceManager.GetString("BusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка данных.....
        /// </summary>
        internal static string busyIndicator {
            get {
                return ResourceManager.GetString("busyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления импорта.
        /// </summary>
        internal static string ErrorDeleteImport {
            get {
                return ResourceManager.GetString("ErrorDeleteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки файла на сервер.
        /// </summary>
        internal static string ErrorFileUpload {
            get {
                return ResourceManager.GetString("ErrorFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные типы дефектов.
        /// </summary>
        internal static string gbDictDefectCompar {
            get {
                return ResourceManager.GetString("gbDictDefectCompar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не связанные типы дефекта из файла импорта.
        /// </summary>
        internal static string gbDictDefectFileImport {
            get {
                return ResourceManager.GetString("gbDictDefectFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы дефектов из БД.
        /// </summary>
        internal static string gbDictDefectTypeBD {
            get {
                return ResourceManager.GetString("gbDictDefectTypeBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало:.
        /// </summary>
        internal static string gbNewImportBegin {
            get {
                return ResourceManager.GetString("gbNewImportBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата:.
        /// </summary>
        internal static string gbNewImportData {
            get {
                return ResourceManager.GetString("gbNewImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор:.
        /// </summary>
        internal static string gbNewImportDogovor {
            get {
                return ResourceManager.GetString("gbNewImportDogovor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец:.
        /// </summary>
        internal static string gbNewImportEnd {
            get {
                return ResourceManager.GetString("gbNewImportEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеральный подрядчик:.
        /// </summary>
        internal static string gbNewImportGenPod {
            get {
                return ResourceManager.GetString("gbNewImportGenPod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель работ:.
        /// </summary>
        internal static string gbNewImportispolWorc {
            get {
                return ResourceManager.GetString("gbNewImportispolWorc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина:.
        /// </summary>
        internal static string gbNewImportLenght {
            get {
                return ResourceManager.GetString("gbNewImportLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МГ:.
        /// </summary>
        internal static string gbNewImportMG {
            get {
                return ResourceManager.GetString("gbNewImportMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нить:.
        /// </summary>
        internal static string gbNewImportPipe {
            get {
                return ResourceManager.GetString("gbNewImportPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место работ:.
        /// </summary>
        internal static string gbNewImportPlaseWork {
            get {
                return ResourceManager.GetString("gbNewImportPlaseWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок:.
        /// </summary>
        internal static string gbNewImportSection {
            get {
                return ResourceManager.GetString("gbNewImportSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленные объекты на участке.
        /// </summary>
        internal static string gbReperLink {
            get {
                return ResourceManager.GetString("gbReperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дефекта из БД.
        /// </summary>
        internal static string grdCompareDefectColumn1 {
            get {
                return ResourceManager.GetString("grdCompareDefectColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название группы.
        /// </summary>
        internal static string grdCompareDefectColumn2 {
            get {
                return ResourceManager.GetString("grdCompareDefectColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип объекта из файла.
        /// </summary>
        internal static string grdCompareDefectColumn3 {
            get {
                return ResourceManager.GetString("grdCompareDefectColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дефекта.
        /// </summary>
        internal static string grdNoRelationColum1 {
            get {
                return ResourceManager.GetString("grdNoRelationColum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дефекта.
        /// </summary>
        internal static string grdTypeDefectColum1 {
            get {
                return ResourceManager.GetString("grdTypeDefectColum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название группы.
        /// </summary>
        internal static string grdTypeDefectColum2 {
            get {
                return ResourceManager.GetString("grdTypeDefectColum2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий статус.
        /// </summary>
        internal static string gridStatecState {
            get {
                return ResourceManager.GetString("gridStatecState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата импорта.
        /// </summary>
        internal static string gridStateDataImport {
            get {
                return ResourceManager.GetString("gridStateDataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата проведения.
        /// </summary>
        internal static string gridStatedateContract {
            get {
                return ResourceManager.GetString("gridStatedateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string gridStateFIO {
            get {
                return ResourceManager.GetString("gridStateFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название файла.
        /// </summary>
        internal static string gridStateNameFile {
            get {
                return ResourceManager.GetString("gridStateNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер договора.
        /// </summary>
        internal static string gridStateNumberContract {
            get {
                return ResourceManager.GetString("gridStateNumberContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок газопровода.
        /// </summary>
        internal static string gridStateSectionPipeline {
            get {
                return ResourceManager.GetString("gridStateSectionPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные по договору.
        /// </summary>
        internal static string groupBoxNewImportDataDog {
            get {
                return ResourceManager.GetString("groupBoxNewImportDataDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные по выбранному участку.
        /// </summary>
        internal static string groupBoxNewImportDataSect {
            get {
                return ResourceManager.GetString("groupBoxNewImportDataSect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла.
        /// </summary>
        internal static string groupBoxNewImportDownLoad {
            get {
                return ResourceManager.GetString("groupBoxNewImportDownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор протяженного объекта.
        /// </summary>
        internal static string groupBoxNewImportVubor {
            get {
                return ResourceManager.GetString("groupBoxNewImportVubor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для данного участка.
        /// </summary>
        internal static string linkNoReperBD {
            get {
                return ResourceManager.GetString("linkNoReperBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для увязывания реперов,  необходимо выбрать строки в соответствующих таблицах.
        /// </summary>
        internal static string Message20 {
            get {
                return ResourceManager.GetString("Message20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка соспоставления строк:.
        /// </summary>
        internal static string Message21 {
            get {
                return ResourceManager.GetString("Message21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не увязаны реперы.
        /// </summary>
        internal static string Message22 {
            get {
                return ResourceManager.GetString("Message22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        internal static string MessageAll {
            get {
                return ResourceManager.GetString("MessageAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления связи..
        /// </summary>
        internal static string MessageBoxDictDefect1 {
            get {
                return ResourceManager.GetString("MessageBoxDictDefect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка увязывания словарей.
        /// </summary>
        internal static string MessageBoxDictDefect2 {
            get {
                return ResourceManager.GetString("MessageBoxDictDefect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перед анализом,  необходимо заполнить по возможности  все поля формы на текущей закладке.
        /// </summary>
        internal static string MessageBoxNewImport1 {
            get {
                return ResourceManager.GetString("MessageBoxNewImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно продолжить импорт, отсутствует ключ пользователя.
        /// </summary>
        internal static string MessageBoxNewImport2 {
            get {
                return ResourceManager.GetString("MessageBoxNewImport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед анализом, необходимо загрузить файл с данными.
        /// </summary>
        internal static string MessageBoxNewImport3 {
            get {
                return ResourceManager.GetString("MessageBoxNewImport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно продолжить импорт, отсутствует ключ пользователя.
        /// </summary>
        internal static string MessageBoxNewImport4 {
            get {
                return ResourceManager.GetString("MessageBoxNewImport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить импорт ВТД?.
        /// </summary>
        internal static string msgDelImport {
            get {
                return ResourceManager.GetString("msgDelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string msgDelImportAttantion {
            get {
                return ResourceManager.GetString("msgDelImportAttantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить импорт, т.к. нет прав на удаление.
        /// </summary>
        internal static string NoDeleteUser {
            get {
                return ResourceManager.GetString("NoDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить попоставление ключей увязанных реперов, импорт остановлен.
        /// </summary>
        internal static string NoReperBuNext {
            get {
                return ResourceManager.GetString("NoReperBuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны данные.
        /// </summary>
        internal static string NoSelect {
            get {
                return ResourceManager.GetString("NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для продолжения импорта необходимо  увязать реперы.
        /// </summary>
        internal static string ReperBuNextMessage {
            get {
                return ResourceManager.GetString("ReperBuNextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реперы из БД.
        /// </summary>
        internal static string Repergb1 {
            get {
                return ResourceManager.GetString("Repergb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реперы из фала импорта ВТД.
        /// </summary>
        internal static string Repergb2 {
            get {
                return ResourceManager.GetString("Repergb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставленный объекты на участке.
        /// </summary>
        internal static string Repergb3 {
            get {
                return ResourceManager.GetString("Repergb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км (м).
        /// </summary>
        internal static string ReperKm {
            get {
                return ResourceManager.GetString("ReperKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км по МГ (м).
        /// </summary>
        internal static string ReperKmOnMGP {
            get {
                return ResourceManager.GetString("ReperKmOnMGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км по ВТД (м).
        /// </summary>
        internal static string ReperKmVTD {
            get {
                return ResourceManager.GetString("ReperKmVTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔКм по МГ (м).
        /// </summary>
        internal static string ReperLenMG {
            get {
                return ResourceManager.GetString("ReperLenMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔКм по ВТД (м).
        /// </summary>
        internal static string ReperLenVTD {
            get {
                return ResourceManager.GetString("ReperLenVTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МК (%).
        /// </summary>
        internal static string ReperMK {
            get {
                return ResourceManager.GetString("ReperMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string ReperName {
            get {
                return ResourceManager.GetString("ReperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер связи.
        /// </summary>
        internal static string ReperNumberLink {
            get {
                return ResourceManager.GetString("ReperNumberLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество секций.
        /// </summary>
        internal static string ReperNumberSec {
            get {
                return ResourceManager.GetString("ReperNumberSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип объекта.
        /// </summary>
        internal static string ReperTypeobj {
            get {
                return ResourceManager.GetString("ReperTypeobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор исходных данных.
        /// </summary>
        internal static string statusChooseImpData {
            get {
                return ResourceManager.GetString("statusChooseImpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словарь дефектов.
        /// </summary>
        internal static string statusDefectsDictionary {
            get {
                return ResourceManager.GetString("statusDefectsDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен с ошибкой.
        /// </summary>
        internal static string statusErrCompl {
            get {
                return ResourceManager.GetString("statusErrCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется импорт.
        /// </summary>
        internal static string statusImportData {
            get {
                return ResourceManager.GetString("statusImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный импорт.
        /// </summary>
        internal static string statusIntroductImport {
            get {
                return ResourceManager.GetString("statusIntroductImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязывание реперов.
        /// </summary>
        internal static string statusLinkReper {
            get {
                return ResourceManager.GetString("statusLinkReper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязывание трубных журналов.
        /// </summary>
        internal static string statusLinkSection {
            get {
                return ResourceManager.GetString("statusLinkSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трубный журнал.
        /// </summary>
        internal static string statusPipeJornal {
            get {
                return ResourceManager.GetString("statusPipeJornal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение файла.
        /// </summary>
        internal static string statusReadFile {
            get {
                return ResourceManager.GetString("statusReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен успешно.
        /// </summary>
        internal static string statusSucessCompl {
            get {
                return ResourceManager.GetString("statusSucessCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словарь дефектов.
        /// </summary>
        internal static string tabItemDictDefect {
            get {
                return ResourceManager.GetString("tabItemDictDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увязывание реперов.
        /// </summary>
        internal static string tabItemLinkReper {
            get {
                return ResourceManager.GetString("tabItemLinkReper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор исходных данных.
        /// </summary>
        internal static string tabItemSelectdate {
            get {
                return ResourceManager.GetString("tabItemSelectdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История изменений.
        /// </summary>
        internal static string tabItemStateProcess {
            get {
                return ResourceManager.GetString("tabItemStateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трубный журнал.
        /// </summary>
        internal static string tabitemTubeJornal {
            get {
                return ResourceManager.GetString("tabitemTubeJornal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История проведения импортов.
        /// </summary>
        internal static string tbNameHistory {
            get {
                return ResourceManager.GetString("tbNameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На выбранном протяженном объекта отсутствует паспорт участка ВТД.
        /// </summary>
        internal static string tbNewImportNoData {
            get {
                return ResourceManager.GetString("tbNewImportNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На выбранном участке ВТД отсутствует паспорт данных внутритрубной дефектоскопии.
        /// </summary>
        internal static string tbNoDataDog {
            get {
                return ResourceManager.GetString("tbNoDataDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На выбранном участке ВТД и на основании договора.
        /// </summary>
        internal static string tbNoDataDog1 {
            get {
                return ResourceManager.GetString("tbNoDataDog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уже ранее был произведен импорт данных ВТД. Для проведения импорта данных на основании договора.
        /// </summary>
        internal static string tbNoDataDog2 {
            get {
                return ResourceManager.GetString("tbNoDataDog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to необходимо удалить предыдущий импорт ВТД, выполненный на его основании.
        /// </summary>
        internal static string tbNoDataDog3 {
            get {
                return ResourceManager.GetString("tbNoDataDog3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите иной номер договора на проведение ВТД.
        /// </summary>
        internal static string tbNoDataDog4 {
            get {
                return ResourceManager.GetString("tbNoDataDog4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат анализа файла.
        /// </summary>
        internal static string tbResultAnalizFile {
            get {
                return ResourceManager.GetString("tbResultAnalizFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км по МГ, м.
        /// </summary>
        internal static string tubeJornalKmMG {
            get {
                return ResourceManager.GetString("tubeJornalKmMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Км по ВТД, м.
        /// </summary>
        internal static string tubeJornalKmVTD {
            get {
                return ResourceManager.GetString("tubeJornalKmVTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина по МГ, м.
        /// </summary>
        internal static string tubeJornalLenghtMG {
            get {
                return ResourceManager.GetString("tubeJornalLenghtMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина по ВТД, м.
        /// </summary>
        internal static string tubeJornalLenghtVTD {
            get {
                return ResourceManager.GetString("tubeJornalLenghtVTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество дефектов.
        /// </summary>
        internal static string tubeJornalNumberD {
            get {
                return ResourceManager.GetString("tubeJornalNumberD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер трубы.
        /// </summary>
        internal static string tubeJornalNumberTube {
            get {
                return ResourceManager.GetString("tubeJornalNumberTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок увязки.
        /// </summary>
        internal static string tubeJornalSecLink {
            get {
                return ResourceManager.GetString("tubeJornalSecLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина стенки, мм.
        /// </summary>
        internal static string tubeJornalThick {
            get {
                return ResourceManager.GetString("tubeJornalThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип трубы.
        /// </summary>
        internal static string tubeJornalType {
            get {
                return ResourceManager.GetString("tubeJornalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор.
        /// </summary>
        internal static string UploadBrowse {
            get {
                return ResourceManager.GetString("UploadBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string UploadCancel {
            get {
                return ResourceManager.GetString("UploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файлы для загрузки.
        /// </summary>
        internal static string UploadCaptionSelect {
            get {
                return ResourceManager.GetString("UploadCaptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбраны файлы:.
        /// </summary>
        internal static string UploadCaptionSelected {
            get {
                return ResourceManager.GetString("UploadCaptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка завершена.
        /// </summary>
        internal static string UploadCaptionUploaded {
            get {
                return ResourceManager.GetString("UploadCaptionUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string UploadCaptionUploading {
            get {
                return ResourceManager.GetString("UploadCaptionUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        internal static string UploadTotal {
            get {
                return ResourceManager.GetString("UploadTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string UploadUpload {
            get {
                return ResourceManager.GetString("UploadUpload", resourceCulture);
            }
        }
    }
}
